### ISSUE TITLE
Unable to load model under CPU-only configuration

### ISSUE THREAD

**Issue by MarkChenYutian** [wang-chen/AirCode#2]
Hi, I want to run object tracking on KITTI tracking datasets with only CPU using the following terminal prompt:

```bash
  python experiments/object_tracking/object_tracking.py -c config/experiment_tracking.yaml -g 1 -s ./results -d /data/datasets/SLAM_dataset/training/ -m ./weights
```
with configuration in `object_tracking.py` updated with

```python
configs['use_gpu'] = 0
```

However, when running with the configuration above with `gcn_model.pth`, `maskrcnn_model.pth`, `points_model.pth` model files in release v2.0.0, the following error occurs:

```
(aircode) yutianc@bender:~/workspace/AirCode$ python experiments/object_tracking/object_tracking.py -c config/experiment_tracking.yaml -g 1 -s ./results -d /data/datasets/SLAM_dataset/training/ -m ./weights
experiments/object_tracking/object_tracking.py:371: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(configs)
Traceback (most recent call last):
  File "experiments/object_tracking/object_tracking.py", line 384, in <module>
    main()
  File "experiments/object_tracking/object_tracking.py", line 381, in main
    show_object_tracking(configs)
  File "experiments/object_tracking/object_tracking.py", line 272, in show_object_tracking
    superpoint_model = build_superpoint_model(configs, requires_grad=False)
  File "./model/build_model.py", line 101, in build_superpoint_model
    model.load_state_dict(model_dict)
  File "/home/yutianc/minicondas/envs/aircode/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VggLike:
        Unexpected key(s) in state_dict: "module.pretrained_net.features.0.weight", "module.pretrained_net.features.0.bias", "module.pretrained_net.features.2.weight", "module.pretrained_net.features.2.bias", "module.pretrained_net.features.5.weight", "module.pretrained_net.features.5.bias", "module.pretrained_net.features.7.weight", "module.pretrained_net.features.7.bias", "module.pretrained_net.features.10.weight", "module.pretrained_net.features.10.bias", "module.pretrained_net.features.12.weight", "module.pretrained_net.features.12.bias", "module.pretrained_net.features.14.weight", "module.pretrained_net.features.14.bias", "module.pretrained_net.features.17.weight", "module.pretrained_net.features.17.bias", "module.pretrained_net.features.19.weight", "module.pretrained_net.features.19.bias", "module.pretrained_net.features.21.weight", "module.pretrained_net.features.21.bias", "module.pretrained_net.features.24.weight", "module.pretrained_net.features.24.bias", "module.pretrained_net.features.26.weight", "module.pretrained_net.features.26.bias", "module.pretrained_net.features.28.weight", "module.pretrained_net.features.28.bias", "module.convPa.weight", "module.convPa.bias", "module.bnPa.weight", "module.bnPa.bias", "module.bnPa.running_mean", "module.bnPa.running_var", "module.bnPa.num_batches_tracked", "module.convPb.weight", "module.convPb.bias", "module.bnPb.weight", "module.bnPb.bias", "module.bnPb.running_mean", "module.bnPb.running_var", "module.bnPb.num_batches_tracked", "module.convDa.weight", "module.convDa.bias", "module.bnDa.weight", "module.bnDa.bias", "module.bnDa.running_mean", "module.bnDa.running_var", "module.bnDa.num_batches_tracked", "module.convDb.weight", "module.convDb.bias", "module.bnDb.weight", "module.bnDb.bias", "module.bnDb.running_mean", "module.bnDb.running_var", "module.bnDb.num_batches_tracked".
```

Running `object_tracking.py` with CUDA seems to load models successfully. Is there something wrong with the model loading when GPU is disabled?

**Comment by xukuanHIT** [comment]
@MarkChenYutian Hi, we trained the model on multi-GPU with "nn.DataParallel", so the keys contain "module.". Please refer to [here](https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686) or [here](https://blog.csdn.net/qq_32998593/article/details/89343507) if you want to run the code with the trained models on the CPU.

**Comment by MarkChenYutian** [comment]
Thanks for reply!

I've converted the model trained with `nn.DataParallel` into CPU version using the following script:

```python
import torch

from collections import OrderedDict

modelNames = ["gcn_model.pth", "maskrcnn_model.pth", "points_model.pth"]

for modelName in modelNames:
    stateDict = torch.load(modelName)
    newStateDict = OrderedDict()
    for k, v in stateDict.items():
        newStateDict[k.replace("module.", "")] = v
    
    torch.save(newStateDict, modelName[:-4] + "_cpu.pth")
```

and the problem is resolved.

**Comment by MarkChenYutian** [comment]
It seems that the `gcn_model` does not respect the configuration of `config['use_gpu'] = 0`. The `maskrcnn` and `point` model is loaded on CPU correctly while the `gcn_model` is still trying to load model with `nn.DataParallel`.

The error message is attached below:

```
(aircode) yutianc@bender:~/workspace/AirCode$ python experiments/object_tracking/object_tracking.py -c config/experiment_tracking.yaml -g 1 -s ./results -d /data/datasets/SLAM_dataset/training/ -m ./weights
experiments/object_tracking/object_tracking.py:371: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(configs)
load model from ./weights/points_model.pth
load model from ./weights/maskrcnn_model.pth
Finish cuda loading
Traceback (most recent call last):
  File "experiments/object_tracking/object_tracking.py", line 384, in <module>
    main()
  File "experiments/object_tracking/object_tracking.py", line 381, in main
    show_object_tracking(configs)
  File "experiments/object_tracking/object_tracking.py", line 278, in show_object_tracking
    gcn_model = build_gcn(configs)
  File "./model/build_model.py", line 121, in build_gcn
    model.load_state_dict(torch.load(pretrained_model_path))
  File "/home/yutianc/minicondas/envs/aircode/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.points_encoder.point_encoder0.weight", "module.points_encoder.point_encoder0.bias", "module.points_encoder.point_encoder1.weight", "module.points_encoder.point_encoder1.bias", "module.points_encoder.point_encoder1.running_mean", "module.points_encoder.point_encoder1.running_var", "module.points_encoder.point_encoder3.weight", "module.points_encoder.point_encoder3.bias", "module.points_encoder.point_encoder4.weight", "module.points_encoder.point_encoder4.bias", "module.points_encoder.point_encoder4.running_mean", "module.points_encoder.point_encoder4.running_var", "module.points_encoder.point_encoder6.weight", "module.points_encoder.point_encoder6.bias", "module.gcn.atten1.attention_0.tranq.weight", "module.gcn.atten1.attention_0.tranq.bias", "module.gcn.atten1.attention_0.trank.weight", "module.gcn.atten1.attention_0.trank.bias", "module.gcn.atten1.attention_0.tranv.weight", "module.gcn.atten1.attention_0.tranv.bias", "module.gcn.atten1.attention_1.tranq.weight", "module.gcn.atten1.attention_1.tranq.bias", "module.gcn.atten1.attention_1.trank.weight", "module.gcn.atten1.attention_1.trank.bias", "module.gcn.atten1.attention_1.tranv.weight", "module.gcn.atten1.attention_1.tranv.bias", "module.gcn.atten1.attention_2.tranq.weight", "module.gcn.atten1.attention_2.tranq.bias", "module.gcn.atten1.attention_2.trank.weight", "module.gcn.atten1.attention_2.trank.bias", "module.gcn.atten1.attention_2.tranv.weight", "module.gcn.atten1.attention_2.tranv.bias", "module.gcn.atten1.attention_3.tranq.weight", "module.gcn.atten1.attention_3.tranq.bias", "module.gcn.atten1.attention_3.trank.weight", "module.gcn.atten1.attention_3.trank.bias", "module.gcn.atten1.attention_3.tranv.weight", "module.gcn.atten1.attention_3.tranv.bias", "module.gcn.atten1.merge.weight", "module.gcn.atten1.merge.bias", "module.gcn.atten1.mlp1.weight", "module.gcn.atten1.mlp1.bias", "module.gcn.atten1.bn1.weight", "module.gcn.atten1.bn1.bias", "module.gcn.atten1.bn1.running_mean", "module.gcn.atten1.bn1.running_var", "module.gcn.atten1.mlp2.weight", "module.gcn.atten1.mlp2.bias", "module.gcn.atten1.bn2.weight", "module.gcn.atten1.bn2.bias", "module.gcn.atten1.bn2.running_mean", "module.gcn.atten1.bn2.running_var", "module.gcn.atten2.attention_0.tranq.weight", "module.gcn.atten2.attention_0.tranq.bias", "module.gcn.atten2.attention_0.trank.weight", "module.gcn.atten2.attention_0.trank.bias", "module.gcn.atten2.attention_0.tranv.weight", "module.gcn.atten2.attention_0.tranv.bias", "module.gcn.atten2.attention_1.tranq.weight", "module.gcn.atten2.attention_1.tranq.bias", "module.gcn.atten2.attention_1.trank.weight", "module.gcn.atten2.attention_1.trank.bias", "module.gcn.atten2.attention_1.tranv.weight", "module.gcn.atten2.attention_1.tranv.bias", "module.gcn.atten2.attention_2.tranq.weight", "module.gcn.atten2.attention_2.tranq.bias", "module.gcn.atten2.attention_2.trank.weight", "module.gcn.atten2.attention_2.trank.bias", "module.gcn.atten2.attention_2.tranv.weight", "module.gcn.atten2.attention_2.tranv.bias", "module.gcn.atten2.attention_3.tranq.weight", "module.gcn.atten2.attention_3.tranq.bias", "module.gcn.atten2.attention_3.trank.weight", "module.gcn.atten2.attention_3.trank.bias", "module.gcn.atten2.attention_3.tranv.weight", "module.gcn.atten2.attention_3.tranv.bias", "module.gcn.atten2.merge.weight", "module.gcn.atten2.merge.bias", "module.gcn.atten2.mlp1.weight", "module.gcn.atten2.mlp1.bias", "module.gcn.atten2.bn1.weight", "module.gcn.atten2.bn1.bias", "module.gcn.atten2.bn1.running_mean", "module.gcn.atten2.bn1.running_var", "module.gcn.atten2.mlp2.weight", "module.gcn.atten2.mlp2.bias", "module.gcn.atten2.bn2.weight", "module.gcn.atten2.bn2.bias", "module.gcn.atten2.bn2.running_mean", "module.gcn.atten2.bn2.running_var", "module.gcn.tran1.weight", "module.gcn.tran1.bias", "module.gcn.sparsification.location_encoder1.weight", "module.gcn.sparsification.location_encoder1.bias", "module.gcn.sparsification.location_encoder2.weight", "module.gcn.sparsification.location_encoder2.bias", "module.gcn.sparsification.feature_encoder1.weight", "module.gcn.sparsification.feature_encoder1.bias", "module.gcn.sparsification.feature_encoder2.weight", "module.gcn.sparsification.feature_encoder2.bias", "module.gcn.sparsification.feature_encoder3.weight", "module.gcn.sparsification.feature_encoder3.bias". 
        Unexpected key(s) in state_dict: "points_encoder.point_encoder0.weight", "points_encoder.point_encoder0.bias", "points_encoder.point_encoder1.weight", "points_encoder.point_encoder1.bias", "points_encoder.point_encoder1.running_mean", "points_encoder.point_encoder1.running_var", "points_encoder.point_encoder1.num_batches_tracked", "points_encoder.point_encoder3.weight", "points_encoder.point_encoder3.bias", "points_encoder.point_encoder4.weight", "points_encoder.point_encoder4.bias", "points_encoder.point_encoder4.running_mean", "points_encoder.point_encoder4.running_var", "points_encoder.point_encoder4.num_batches_tracked", "points_encoder.point_encoder6.weight", "points_encoder.point_encoder6.bias", "gcn.atten1.attention_0.tranq.weight", "gcn.atten1.attention_0.tranq.bias", "gcn.atten1.attention_0.trank.weight", "gcn.atten1.attention_0.trank.bias", "gcn.atten1.attention_0.tranv.weight", "gcn.atten1.attention_0.tranv.bias", "gcn.atten1.attention_1.tranq.weight", "gcn.atten1.attention_1.tranq.bias", "gcn.atten1.attention_1.trank.weight", "gcn.atten1.attention_1.trank.bias", "gcn.atten1.attention_1.tranv.weight", "gcn.atten1.attention_1.tranv.bias", "gcn.atten1.attention_2.tranq.weight", "gcn.atten1.attention_2.tranq.bias", "gcn.atten1.attention_2.trank.weight", "gcn.atten1.attention_2.trank.bias", "gcn.atten1.attention_2.tranv.weight", "gcn.atten1.attention_2.tranv.bias", "gcn.atten1.attention_3.tranq.weight", "gcn.atten1.attention_3.tranq.bias", "gcn.atten1.attention_3.trank.weight", "gcn.atten1.attention_3.trank.bias", "gcn.atten1.attention_3.tranv.weight", "gcn.atten1.attention_3.tranv.bias", "gcn.atten1.merge.weight", "gcn.atten1.merge.bias", "gcn.atten1.mlp1.weight", "gcn.atten1.mlp1.bias", "gcn.atten1.bn1.weight", "gcn.atten1.bn1.bias", "gcn.atten1.bn1.running_mean", "gcn.atten1.bn1.running_var", "gcn.atten1.bn1.num_batches_tracked", "gcn.atten1.mlp2.weight", "gcn.atten1.mlp2.bias", "gcn.atten1.bn2.weight", "gcn.atten1.bn2.bias", "gcn.atten1.bn2.running_mean", "gcn.atten1.bn2.running_var", "gcn.atten1.bn2.num_batches_tracked", "gcn.atten2.attention_0.tranq.weight", "gcn.atten2.attention_0.tranq.bias", "gcn.atten2.attention_0.trank.weight", "gcn.atten2.attention_0.trank.bias", "gcn.atten2.attention_0.tranv.weight", "gcn.atten2.attention_0.tranv.bias", "gcn.atten2.attention_1.tranq.weight", "gcn.atten2.attention_1.tranq.bias", "gcn.atten2.attention_1.trank.weight", "gcn.atten2.attention_1.trank.bias", "gcn.atten2.attention_1.tranv.weight", "gcn.atten2.attention_1.tranv.bias", "gcn.atten2.attention_2.tranq.weight", "gcn.atten2.attention_2.tranq.bias", "gcn.atten2.attention_2.trank.weight", "gcn.atten2.attention_2.trank.bias", "gcn.atten2.attention_2.tranv.weight", "gcn.atten2.attention_2.tranv.bias", "gcn.atten2.attention_3.tranq.weight", "gcn.atten2.attention_3.tranq.bias", "gcn.atten2.attention_3.trank.weight", "gcn.atten2.attention_3.trank.bias", "gcn.atten2.attention_3.tranv.weight", "gcn.atten2.attention_3.tranv.bias", "gcn.atten2.merge.weight", "gcn.atten2.merge.bias", "gcn.atten2.mlp1.weight", "gcn.atten2.mlp1.bias", "gcn.atten2.bn1.weight", "gcn.atten2.bn1.bias", "gcn.atten2.bn1.running_mean", "gcn.atten2.bn1.running_var", "gcn.atten2.bn1.num_batches_tracked", "gcn.atten2.mlp2.weight", "gcn.atten2.mlp2.bias", "gcn.atten2.bn2.weight", "gcn.atten2.bn2.bias", "gcn.atten2.bn2.running_mean", "gcn.atten2.bn2.running_var", "gcn.atten2.bn2.num_batches_tracked", "gcn.tran1.weight", "gcn.tran1.bias", "gcn.sparsification.location_encoder1.weight", "gcn.sparsification.location_encoder1.bias", "gcn.sparsification.location_encoder2.weight", "gcn.sparsification.location_encoder2.bias", "gcn.sparsification.feature_encoder1.weight", "gcn.sparsification.feature_encoder1.bias", "gcn.sparsification.feature_encoder2.weight", "gcn.sparsification.feature_encoder2.bias", "gcn.sparsification.feature_encoder3.weight", "gcn.sparsification.feature_encoder3.bias". 
```

**Comment by MarkChenYutian** [comment]
Resolved after changing `line261` of `experiments/object_tracking.py`  into this:

```python
configs['num_gpu'] = [0] if configs['use_gpu'] else []
```
